AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/initializers/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 10

Metrics/AbcSize:
  Max: 25

Documentation:
  Enabled: false